/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.keedio.flume.interceptor.enrichment.serialization.avro.specific;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EnrichedEventBodyGenericAvroString extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrichedEventBodyGenericAvroString\",\"namespace\":\"org.keedio.flume.interceptor.enrichment.interceptor\",\"fields\":[{\"name\":\"extraData\",\"type\":{\"type\":\"record\",\"name\":\"EnrichedEventBodyExtraDataAvroString\",\"fields\":[{\"name\":\"topic\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"timestamp\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"sha1Hex\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"filePath\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"fileName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"lineNumber\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public EnrichedEventBodyExtraDataAvroString extraData;
  @Deprecated public java.lang.String message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EnrichedEventBodyGenericAvroString() {}

  /**
   * All-args constructor.
   */
  public EnrichedEventBodyGenericAvroString(EnrichedEventBodyExtraDataAvroString extraData, java.lang.String message) {
    this.extraData = extraData;
    this.message = message;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return extraData;
    case 1: return message;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: extraData = (EnrichedEventBodyExtraDataAvroString)value$; break;
    case 1: message = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'extraData' field.
   */
  public EnrichedEventBodyExtraDataAvroString getExtraData() {
    return extraData;
  }

  /**
   * Sets the value of the 'extraData' field.
   * @param value the value to set.
   */
  public void setExtraData(EnrichedEventBodyExtraDataAvroString value) {
    this.extraData = value;
  }

  /**
   * Gets the value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /** Creates a new EnrichedEventBodyGenericAvroString RecordBuilder */
  public static EnrichedEventBodyGenericAvroString.Builder newBuilder() {
    return new EnrichedEventBodyGenericAvroString.Builder();
  }
  
  /** Creates a new EnrichedEventBodyGenericAvroString RecordBuilder by copying an existing Builder */
  public static EnrichedEventBodyGenericAvroString.Builder newBuilder(EnrichedEventBodyGenericAvroString.Builder other) {
    return new EnrichedEventBodyGenericAvroString.Builder(other);
  }
  
  /** Creates a new EnrichedEventBodyGenericAvroString RecordBuilder by copying an existing EnrichedEventBodyGenericAvroString instance */
  public static EnrichedEventBodyGenericAvroString.Builder newBuilder(EnrichedEventBodyGenericAvroString other) {
    return new EnrichedEventBodyGenericAvroString.Builder(other);
  }
  
  /**
   * RecordBuilder for EnrichedEventBodyGenericAvroString instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrichedEventBodyGenericAvroString>
    implements org.apache.avro.data.RecordBuilder<EnrichedEventBodyGenericAvroString> {

    private EnrichedEventBodyExtraDataAvroString extraData;
    private java.lang.String message;

    /** Creates a new Builder */
    private Builder() {
      super(EnrichedEventBodyGenericAvroString.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(EnrichedEventBodyGenericAvroString.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.extraData)) {
        this.extraData = data().deepCopy(fields()[0].schema(), other.extraData);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EnrichedEventBodyGenericAvroString instance */
    private Builder(EnrichedEventBodyGenericAvroString other) {
            super(EnrichedEventBodyGenericAvroString.SCHEMA$);
      if (isValidValue(fields()[0], other.extraData)) {
        this.extraData = data().deepCopy(fields()[0].schema(), other.extraData);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.message)) {
        this.message = data().deepCopy(fields()[1].schema(), other.message);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'extraData' field */
    public EnrichedEventBodyExtraDataAvroString getExtraData() {
      return extraData;
    }
    
    /** Sets the value of the 'extraData' field */
    public EnrichedEventBodyGenericAvroString.Builder setExtraData(EnrichedEventBodyExtraDataAvroString value) {
      validate(fields()[0], value);
      this.extraData = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'extraData' field has been set */
    public boolean hasExtraData() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'extraData' field */
    public EnrichedEventBodyGenericAvroString.Builder clearExtraData() {
      extraData = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'message' field */
    public java.lang.String getMessage() {
      return message;
    }
    
    /** Sets the value of the 'message' field */
    public EnrichedEventBodyGenericAvroString.Builder setMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.message = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'message' field has been set */
    public boolean hasMessage() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'message' field */
    public EnrichedEventBodyGenericAvroString.Builder clearMessage() {
      message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public EnrichedEventBodyGenericAvroString build() {
      try {
        EnrichedEventBodyGenericAvroString record = new EnrichedEventBodyGenericAvroString();
        record.extraData = fieldSetFlags()[0] ? this.extraData : (EnrichedEventBodyExtraDataAvroString) defaultValue(fields()[0]);
        record.message = fieldSetFlags()[1] ? this.message : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
