/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.keedio.flume.interceptor.enrichment.serialization.avro.specific;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EnrichedEventBodyMapAvroString extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrichedEventBodyMapAvroString\",\"namespace\":\"org.keedio.flume.interceptor.enrichment.interceptor\",\"fields\":[{\"name\":\"extraData\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
    @Deprecated public java.util.Map<java.lang.String,java.lang.String> extraData;
    @Deprecated public java.lang.String message;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public EnrichedEventBodyMapAvroString() {}

    /**
     * All-args constructor.
     */
    public EnrichedEventBodyMapAvroString(java.util.Map<java.lang.String,java.lang.String> extraData, java.lang.String message) {
        this.extraData = extraData;
        this.message = message;
    }

    public org.apache.avro.Schema getSchema() { return SCHEMA$; }
    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return extraData;
            case 1: return message;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: extraData = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
            case 1: message = (java.lang.String)value$; break;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'extraData' field.
     */
    public java.util.Map<java.lang.String,java.lang.String> getExtraData() {
        return extraData;
    }

    /**
     * Sets the value of the 'extraData' field.
     * @param value the value to set.
     */
    public void setExtraData(java.util.Map<java.lang.String,java.lang.String> value) {
        this.extraData = value;
    }

    /**
     * Gets the value of the 'message' field.
     */
    public java.lang.String getMessage() {
        return message;
    }

    /**
     * Sets the value of the 'message' field.
     * @param value the value to set.
     */
    public void setMessage(java.lang.String value) {
        this.message = value;
    }

    /** Creates a new EnrichedEventBodyMapAvroString RecordBuilder */
    public static EnrichedEventBodyMapAvroString.Builder newBuilder() {
        return new EnrichedEventBodyMapAvroString.Builder();
    }

    /** Creates a new EnrichedEventBodyMapAvroString RecordBuilder by copying an existing Builder */
    public static EnrichedEventBodyMapAvroString.Builder newBuilder(EnrichedEventBodyMapAvroString.Builder other) {
        return new EnrichedEventBodyMapAvroString.Builder(other);
    }

    /** Creates a new EnrichedEventBodyMapAvroString RecordBuilder by copying an existing EnrichedEventBodyMapAvroString instance */
    public static EnrichedEventBodyMapAvroString.Builder newBuilder(EnrichedEventBodyMapAvroString other) {
        return new EnrichedEventBodyMapAvroString.Builder(other);
    }

    /**
     * RecordBuilder for EnrichedEventBodyMapAvroString instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrichedEventBodyMapAvroString>
            implements org.apache.avro.data.RecordBuilder<EnrichedEventBodyMapAvroString> {

        private java.util.Map<java.lang.String,java.lang.String> extraData;
        private java.lang.String message;

        /** Creates a new Builder */
        private Builder() {
            super(EnrichedEventBodyMapAvroString.SCHEMA$);
        }

        /** Creates a Builder by copying an existing Builder */
        private Builder(EnrichedEventBodyMapAvroString.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.extraData)) {
                this.extraData = data().deepCopy(fields()[0].schema(), other.extraData);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.message)) {
                this.message = data().deepCopy(fields()[1].schema(), other.message);
                fieldSetFlags()[1] = true;
            }
        }

        /** Creates a Builder by copying an existing EnrichedEventBodyMapAvroString instance */
        private Builder(EnrichedEventBodyMapAvroString other) {
            super(EnrichedEventBodyMapAvroString.SCHEMA$);
            if (isValidValue(fields()[0], other.extraData)) {
                this.extraData = data().deepCopy(fields()[0].schema(), other.extraData);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.message)) {
                this.message = data().deepCopy(fields()[1].schema(), other.message);
                fieldSetFlags()[1] = true;
            }
        }

        /** Gets the value of the 'extraData' field */
        public java.util.Map<java.lang.String,java.lang.String> getExtraData() {
            return extraData;
        }

        /** Sets the value of the 'extraData' field */
        public EnrichedEventBodyMapAvroString.Builder setExtraData(java.util.Map<java.lang.String,java.lang.String> value) {
            validate(fields()[0], value);
            this.extraData = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /** Checks whether the 'extraData' field has been set */
        public boolean hasExtraData() {
            return fieldSetFlags()[0];
        }

        /** Clears the value of the 'extraData' field */
        public EnrichedEventBodyMapAvroString.Builder clearExtraData() {
            extraData = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /** Gets the value of the 'message' field */
        public java.lang.String getMessage() {
            return message;
        }

        /** Sets the value of the 'message' field */
        public EnrichedEventBodyMapAvroString.Builder setMessage(java.lang.String value) {
            validate(fields()[1], value);
            this.message = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /** Checks whether the 'message' field has been set */
        public boolean hasMessage() {
            return fieldSetFlags()[1];
        }

        /** Clears the value of the 'message' field */
        public EnrichedEventBodyMapAvroString.Builder clearMessage() {
            message = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        public EnrichedEventBodyMapAvroString build() {
            try {
                EnrichedEventBodyMapAvroString record = new EnrichedEventBodyMapAvroString();
                record.extraData = fieldSetFlags()[0] ? this.extraData : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[0]);
                record.message = fieldSetFlags()[1] ? this.message : (java.lang.String) defaultValue(fields()[1]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}

