/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.keedio.flume.interceptor.enrichment.serialization.avro.specific;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EnrichedEventBodyExtraDataAvroString extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EnrichedEventBodyExtraDataAvroString\",\"namespace\":\"org.keedio.flume.interceptor.enrichment.interceptor\",\"fields\":[{\"name\":\"topic\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"timestamp\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"sha1Hex\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"filePath\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"fileName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"lineNumber\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"type\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String topic;
  @Deprecated public java.lang.String timestamp;
  @Deprecated public java.lang.String sha1Hex;
  @Deprecated public java.lang.String filePath;
  @Deprecated public java.lang.String fileName;
  @Deprecated public java.lang.String lineNumber;
  @Deprecated public java.lang.String type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public EnrichedEventBodyExtraDataAvroString() {}

  /**
   * All-args constructor.
   */
  public EnrichedEventBodyExtraDataAvroString(java.lang.String topic, java.lang.String timestamp, java.lang.String sha1Hex, java.lang.String filePath, java.lang.String fileName, java.lang.String lineNumber, java.lang.String type) {
    this.topic = topic;
    this.timestamp = timestamp;
    this.sha1Hex = sha1Hex;
    this.filePath = filePath;
    this.fileName = fileName;
    this.lineNumber = lineNumber;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return topic;
    case 1: return timestamp;
    case 2: return sha1Hex;
    case 3: return filePath;
    case 4: return fileName;
    case 5: return lineNumber;
    case 6: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: topic = (java.lang.String)value$; break;
    case 1: timestamp = (java.lang.String)value$; break;
    case 2: sha1Hex = (java.lang.String)value$; break;
    case 3: filePath = (java.lang.String)value$; break;
    case 4: fileName = (java.lang.String)value$; break;
    case 5: lineNumber = (java.lang.String)value$; break;
    case 6: type = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'topic' field.
   */
  public java.lang.String getTopic() {
    return topic;
  }

  /**
   * Sets the value of the 'topic' field.
   * @param value the value to set.
   */
  public void setTopic(java.lang.String value) {
    this.topic = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   */
  public java.lang.String getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.String value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'sha1Hex' field.
   */
  public java.lang.String getSha1Hex() {
    return sha1Hex;
  }

  /**
   * Sets the value of the 'sha1Hex' field.
   * @param value the value to set.
   */
  public void setSha1Hex(java.lang.String value) {
    this.sha1Hex = value;
  }

  /**
   * Gets the value of the 'filePath' field.
   */
  public java.lang.String getFilePath() {
    return filePath;
  }

  /**
   * Sets the value of the 'filePath' field.
   * @param value the value to set.
   */
  public void setFilePath(java.lang.String value) {
    this.filePath = value;
  }

  /**
   * Gets the value of the 'fileName' field.
   */
  public java.lang.String getFileName() {
    return fileName;
  }

  /**
   * Sets the value of the 'fileName' field.
   * @param value the value to set.
   */
  public void setFileName(java.lang.String value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'lineNumber' field.
   */
  public java.lang.String getLineNumber() {
    return lineNumber;
  }

  /**
   * Sets the value of the 'lineNumber' field.
   * @param value the value to set.
   */
  public void setLineNumber(java.lang.String value) {
    this.lineNumber = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /** Creates a new EnrichedEventBodyExtraDataAvroString RecordBuilder */
  public static EnrichedEventBodyExtraDataAvroString.Builder newBuilder() {
    return new EnrichedEventBodyExtraDataAvroString.Builder();
  }
  
  /** Creates a new EnrichedEventBodyExtraDataAvroString RecordBuilder by copying an existing Builder */
  public static EnrichedEventBodyExtraDataAvroString.Builder newBuilder(EnrichedEventBodyExtraDataAvroString.Builder other) {
    return new EnrichedEventBodyExtraDataAvroString.Builder(other);
  }
  
  /** Creates a new EnrichedEventBodyExtraDataAvroString RecordBuilder by copying an existing EnrichedEventBodyExtraDataAvroString instance */
  public static EnrichedEventBodyExtraDataAvroString.Builder newBuilder(EnrichedEventBodyExtraDataAvroString other) {
    return new EnrichedEventBodyExtraDataAvroString.Builder(other);
  }
  
  /**
   * RecordBuilder for EnrichedEventBodyExtraDataAvroString instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EnrichedEventBodyExtraDataAvroString>
    implements org.apache.avro.data.RecordBuilder<EnrichedEventBodyExtraDataAvroString> {

    private java.lang.String topic;
    private java.lang.String timestamp;
    private java.lang.String sha1Hex;
    private java.lang.String filePath;
    private java.lang.String fileName;
    private java.lang.String lineNumber;
    private java.lang.String type;

    /** Creates a new Builder */
    private Builder() {
      super(EnrichedEventBodyExtraDataAvroString.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(EnrichedEventBodyExtraDataAvroString.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sha1Hex)) {
        this.sha1Hex = data().deepCopy(fields()[2].schema(), other.sha1Hex);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.filePath)) {
        this.filePath = data().deepCopy(fields()[3].schema(), other.filePath);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fileName)) {
        this.fileName = data().deepCopy(fields()[4].schema(), other.fileName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lineNumber)) {
        this.lineNumber = data().deepCopy(fields()[5].schema(), other.lineNumber);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.type)) {
        this.type = data().deepCopy(fields()[6].schema(), other.type);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing EnrichedEventBodyExtraDataAvroString instance */
    private Builder(EnrichedEventBodyExtraDataAvroString other) {
            super(EnrichedEventBodyExtraDataAvroString.SCHEMA$);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.sha1Hex)) {
        this.sha1Hex = data().deepCopy(fields()[2].schema(), other.sha1Hex);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.filePath)) {
        this.filePath = data().deepCopy(fields()[3].schema(), other.filePath);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fileName)) {
        this.fileName = data().deepCopy(fields()[4].schema(), other.fileName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lineNumber)) {
        this.lineNumber = data().deepCopy(fields()[5].schema(), other.lineNumber);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.type)) {
        this.type = data().deepCopy(fields()[6].schema(), other.type);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'topic' field */
    public java.lang.String getTopic() {
      return topic;
    }
    
    /** Sets the value of the 'topic' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setTopic(java.lang.String value) {
      validate(fields()[0], value);
      this.topic = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'topic' field has been set */
    public boolean hasTopic() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'topic' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearTopic() {
      topic = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'timestamp' field */
    public java.lang.String getTimestamp() {
      return timestamp;
    }
    
    /** Sets the value of the 'timestamp' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setTimestamp(java.lang.String value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'timestamp' field has been set */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'timestamp' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'sha1Hex' field */
    public java.lang.String getSha1Hex() {
      return sha1Hex;
    }
    
    /** Sets the value of the 'sha1Hex' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setSha1Hex(java.lang.String value) {
      validate(fields()[2], value);
      this.sha1Hex = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'sha1Hex' field has been set */
    public boolean hasSha1Hex() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'sha1Hex' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearSha1Hex() {
      sha1Hex = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'filePath' field */
    public java.lang.String getFilePath() {
      return filePath;
    }
    
    /** Sets the value of the 'filePath' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setFilePath(java.lang.String value) {
      validate(fields()[3], value);
      this.filePath = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'filePath' field has been set */
    public boolean hasFilePath() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'filePath' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearFilePath() {
      filePath = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'fileName' field */
    public java.lang.String getFileName() {
      return fileName;
    }
    
    /** Sets the value of the 'fileName' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setFileName(java.lang.String value) {
      validate(fields()[4], value);
      this.fileName = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'fileName' field has been set */
    public boolean hasFileName() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'fileName' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'lineNumber' field */
    public java.lang.String getLineNumber() {
      return lineNumber;
    }
    
    /** Sets the value of the 'lineNumber' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setLineNumber(java.lang.String value) {
      validate(fields()[5], value);
      this.lineNumber = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'lineNumber' field has been set */
    public boolean hasLineNumber() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'lineNumber' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearLineNumber() {
      lineNumber = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public java.lang.String getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public EnrichedEventBodyExtraDataAvroString.Builder setType(java.lang.String value) {
      validate(fields()[6], value);
      this.type = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'type' field */
    public EnrichedEventBodyExtraDataAvroString.Builder clearType() {
      type = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public EnrichedEventBodyExtraDataAvroString build() {
      try {
        EnrichedEventBodyExtraDataAvroString record = new EnrichedEventBodyExtraDataAvroString();
        record.topic = fieldSetFlags()[0] ? this.topic : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.String) defaultValue(fields()[1]);
        record.sha1Hex = fieldSetFlags()[2] ? this.sha1Hex : (java.lang.String) defaultValue(fields()[2]);
        record.filePath = fieldSetFlags()[3] ? this.filePath : (java.lang.String) defaultValue(fields()[3]);
        record.fileName = fieldSetFlags()[4] ? this.fileName : (java.lang.String) defaultValue(fields()[4]);
        record.lineNumber = fieldSetFlags()[5] ? this.lineNumber : (java.lang.String) defaultValue(fields()[5]);
        record.type = fieldSetFlags()[6] ? this.type : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
